#!/opt/homebrew/bin/bash
# remember to change this when deploying. to #!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

# Constants & Configuration
REFRESH_INTERVAL=5
WATCH_MODE=false
VERSION="1.0.0"
SCRIPT_NAME=$(basename $0)

# CPU/MEM thresholds for color coding
CPU_WARN=50 # % — green below, yellow above
CPU_CRIT=80 # % — red above
MEM_WARN=60 # % — green below, yellow above
MEM_CRIT=85 # % — red above

# ------------------------------------------------------------------------------
# COLORS & FORMATTING (degrade gracefully if terminal doesn't support them)
# ------------------------------------------------------------------------------
if tput colors &> /dev/null && (( $(tput colors) >= 8 )); then
    RESET=$(tput sgr0)
    BOLD=$(tput bold)
    DIM=$(tput dim)
    RED=$(tput setaf 1)
    GREEN=$(tput setaf 2)
    YELLOW=$(tput setaf 3)
    BLUE=$(tput setaf 4)
    CYAN=$(tput setaf 6)
    WHITE=$(tput setaf 7)
else
    RESET=""BOLD=""DIM=""
    RED=""GREEN=""YELLOW=""BLUE=""CYAN=""WHITE=""
fi

# ------------------------------------------------------------------------------
# LOGGING HELPERS
# ------------------------------------------------------------------------------
log_info() { echo "${CYAN}[INFO] ${RESET}$*"; }
log_warn() { echo "${YELLOW}[WARN] ${RESET}$*" >&2;}
log_error() { echo "${RED}[ERROR] ${RESET}$*" >&2; }

while getopts ":wi:hv" opt; do
    case $opt in
        w) WATCH_MODE=true ;;
        i) REFRESH_INTERVAL="$OPTARG" ;;
        h) usage; exit 0;;
        v) log_info "v${VERSION}"; exit 0;;
        :) log_error "Option -${OPTARG} require an argument."; exit 1;;
        \?) log_error "Unknown option -${OPTARG}"; exit 1;;
    esac
done

if ! [[ "$REFRESH_INTERVAL" =~ ^[1-9]+$ ]] || (( "$REFRESH_INTERVAL" < 0 )); then
    echo "Interval must be a positive integer."
    exit 1;
fi

check_dependencies() {
    local missing=()

    for cmd in docker awk tput; do
        if ! command -v "$cmd" &>/dev/null; then
            missing+=("$cmd")
        fi
    done

    if (( "${#missing[@]}" > 0 )); then
        echo "Missing dependencies- ${missing[*]}";
        exit 1;
    fi

    if ! docker info &>/dev/null; then
        echo "Cannot connect to Docker daemon";
        exit 1;
    fi
}